config/routes.rb
Rails.application.routes.draw do
  get 'bmi', to: "bmi#index"
  post "bmi/result", to: "bmi#result"


  resources :candidates do
  	member do
  		post :vote
  	end
  end

  root 'candidates#index'







  # get "hello_world", to: "pages#hello"
  # resources :posts
  # resources :users




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bmi_controller.rb
class BmiController < ApplicationController
  def index
  end


  def result
  	height = params[:body_height].to_f / 100
  	weight = params[:body_weight].to_f

  	@bmi = (weight / (height * height)).round(2)
  	
  end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	

	before_action :find_candidate, only: [:edit, :update, :destroy, :vote]

	#程式執行action之前會先呼叫set_event方法,並指定




	def index
		@candidates = Candidate.all

	end

	def new
		@candidate = Candidate.new
		
		
	end

	
	def edit
		#兩種find寫法都行
		# @candidate = Candidate.find_by(id: params[:id])

		# 使用了befroe_action 所以下面這行可以省略
		# @candidate = Candidate.find(params[:id])
		
	end

	def update
		# 使用了befroe_action 所以下面這行可以省略
		#@candidate = Candidate.find(params[:id])

	    if @candidate.update_attributes(candidate_params)
	      # 成功
	      redirect_to candidates_path, notice: "資料更新成功!"
	    else
	      # 失敗
	      render :edit
	    end
	end


	def create
		#修改前
		#@candidate = Candidate.new(params[:candidate])

		#修改後
		@candidate = Candidate.new(candidate_params)

		if @candidate.save
			#成功
			redirect_to candidates_path, notice: "新增候選人成功！"
		else
			#失敗
			render :new
		end
	end


	def destroy
		# 使用了befroe_action 所以下面這行可以省略
		# @candidate = Candidate.find(params[:id])
    	@candidate.destroy if @candidate
    	redirect_to candidates_path, notice: "候選人資料已刪除!"
	end


	def vote
		# 使用了befroe_action 所以下面這行可以省略
		# @candidate = Candidate.find(params[:id])
		@candidate.increment(:votes)
		@candidate.save
		redirect_to candidates_path, notice: "完成投票"
	end




	private

	def candidate_params
		params.require(:candidate).permit(:name, :age, :party, :politics)
	end

	def find_candidate
		@candidate = Candidate.find(params[:id])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def hello
  	render json: params[:name]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(5)

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :is_available)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :tel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmi_helper.rb
module BmiHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bmi/index.html.erb
<h1>BMI 計算機</h1>

<%= form_tag '/bmi/result' do %>
	身高： <%= text_field_tag 'body_height' %>公分 <br>
	體重： <%= text_field_tag 'body_weight' %>公斤 <br>
	<%= submit_tag "開始計算" %>
<% end %>

app/views/bmi/result.html.erb
<h1>您的 BMI 值為 <%= @bmi %></h1>

app/views/candidates/_form.html.erb
<!--
舊的
<%= form_for @candidate do |f| %>
	<%= f.label :name, "姓名" %>
	<%= f.text_field :name %> <br>

	<%= f.label :age, "年齡" %>
	<%= f.text_field :age %> <br>

	<%= f.label :party, "政黨" %>
	<%= f.text_field :party %> <br>

	<%= f.label :politics, "政見" %>
	<%= f.text_area :politics %> <br>

	<%= f.submit %>
<% end %>
-->

<!-- 下面這行用gem simple_form 結合bootstrap改寫 -->
<%= simple_form_for @candidate do |f| %>
	<%= f.input :name, label: "姓名" %>
	<%= f.input :age, label: "年齡" %>
	<%= f.input :party, label: "政黨" %>
	<%= f.input :politics, label: "政見" %>
	<%= f.submit %>
<% end %>



<br>
<%= link_to "回候選人列表", candidates_path %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>


<!--
<%= form_for @candidate do |f| %>
	<%= f.label :name, "姓名" %>
	<%= f.text_field :name %> <br>

	<%= f.label :age, "年齡" %>
	<%= f.text_field :age %> <br>

	<%= f.label :party, "政黨" %>
	<%= f.text_field :party %> <br>

	<%= f.label :politics, "政見" %>
	<%= f.text_area :politics %> <br>

	<%= f.submit %>
<% end %>

<br>
<%= link_to "回候選人列表", candidates_path %>

-->

<%= render "form" %>

app/views/candidates/index.html.erb
 <!-- 使用provide 填坑  -->
<% provide :my_title, "你好，我是Ken" %> 






<h1>候選人列表</h1>

<%= link_to "新增候選人", new_candidate_path %>

<table class="table">
	<thead>
		<tr>
      <td>投票</td>
			<td>候選人姓名</td>
			<td>政黨</td>
			<td>政見</td>
			<td>得票數</td>
      <td>處理</td>
		</tr>
	</thead>
	<tbody>
		<% @candidates.each do |candidate| %>
		<tr>
      <td><%= link_to "投給這位", vote_candidate_path(candidate), method: "post", data: { confirm: "確認要投給這位候選人嗎?!"}, class:"btn btn-danger btn-xs" %></td>
			<td><%= candidate.name %>(年齡： <%= candidate.age %> 歲)</td>
			<td><%= candidate.party %></td>
			<td><%= candidate.politics %></td>
			<td><%= candidate.votes %></td>
      <td>
        <%= link_to "編輯", edit_candidate_path(candidate) %>
        <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除"} %>
      </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<!--
<%= form_for @candidate do |f| %> 
	<%= f.label :name, "姓名" %>
	<%= f.text_field :name %> <br>

	<%= f.label :age, "年齡" %>
	<%= f.text_field :age %> <br>

	<%= f.label :party, "政黨" %>
	<%= f.text_field :party %> <br>

	<%= f.label :politics, "政見" %>
	<%= f.text_area :politics %> <br>

	<%= f.submit %>
<% end %>

<br>
<%= link_to "回候選人列表", candidates_path %>
-->


<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :my_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
    	<%= yield %>


  	</div>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>網站管理系統</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>我是後台</h1>
  	<div class="container">
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>你好，世界</h1>
<h2>我要變得更厲害</h2>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :is_available %>
    <%= f.check_box :is_available %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Is available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= post.is_available %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Post', new_post_path %>
<br>
<br>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @post.is_available %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :tel %>
    <%= f.text_field :tel %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tel %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>